export const storageKeys = {
  user: "user",
  trainerPhone: "trainerPhone",
  trainerName: "trainerName",
  trainerEmail: "trainerEmail",
  termsAgreement: "termsAgreement",
  trainerSnsKind: "trainerSnsKind",
  terms: "terms",
  activeCenterId: "activeCenterId",
  auth: "auth",
  revenueActiveDate: "revenueActiveDate",
  ticketActiveFilter: "ticketActiveFilter",
  signatureActiveDate: "signatureActiveDate",
  selectedTerm: "selectedTerm",
  assignNewTraineeValues: "assignNewTraineeValues",
  assignNewTraineeFormValues: "assignNewTraineeFormValues",
};
